# Generated by Django 2.1.7 on 2019-03-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthcontact',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
