# Generated by Django 2.1.7 on 2019-03-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_channelcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelcontact',
            name='distribution_channel',
            field=models.IntegerField(default=0),
        ),
    ]
