# Generated by Django 2.1.7 on 2019-03-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
