# Generated by Django 2.1.7 on 2019-03-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190329_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chanel', models.CharField(max_length=200)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ChannelContact')),
            ],
        ),
    ]
