# Generated by Django 2.1.7 on 2019-03-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='channelcontact',
            name='distribution_channel',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
