# Generated by Django 2.1.7 on 2019-03-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='ChannelContact',
        ),
    ]
