# Generated by Django 2.1.7 on 2019-03-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190329_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_channel', models.IntegerField(default=0)),
                ('name_chanel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_customer', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Channel')),
            ],
        ),
    ]
