# Generated by Django 2.1.7 on 2019-03-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_channel_channelcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='distribution_channel',
        ),
    ]
