# Generated by Django 2.1.7 on 2019-03-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_channel_distribution_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
