# Generated by Django 2.1.7 on 2019-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190330_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_agent', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
