# Generated by Django 2.1.7 on 2019-03-31 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_newagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_agent', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(null=True)),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Channel')),
            ],
        ),
    ]
