# Generated by Django 2.1.7 on 2019-04-01 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_agentchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentchannel',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Channel'),
        ),
    ]
