# Generated by Django 2.1.7 on 2019-04-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190401_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_customer', models.IntegerField(default=0)),
                ('number_policy', models.IntegerField(default=0)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Channel')),
            ],
        ),
    ]
