# Generated by Django 2.1.7 on 2019-04-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_channelsuccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsuccess',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
