# Generated by Django 2.1.7 on 2019-04-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_locationcontact_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcontact',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Province'),
        ),
    ]
