# Generated by Django 2.1.7 on 2019-04-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20190405_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycontact',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
