# Generated by Django 2.1.7 on 2019-04-05 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20190405_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Product_Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_customer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MainBenefit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_benefit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='main_product_benefit',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MainBenefit'),
        ),
        migrations.AddField(
            model_name='main_product_benefit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MainProduct'),
        ),
    ]
