# Generated by Django 2.1.7 on 2019-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20190405_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product_benefit',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
