# Generated by Django 2.1.7 on 2019-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_main_product_benefit_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_product_benefit',
            name='number_customer',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='number_customer',
            field=models.IntegerField(default=0),
        ),
    ]
