# Generated by Django 2.1.7 on 2019-04-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20190405_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_product_benefit',
            name='created_time',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
