# Generated by Django 2.1.7 on 2019-04-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20190416_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sup_Product_Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MainBenefit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MainProduct')),
            ],
        ),
        migrations.CreateModel(
            name='SupBenefit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_benefit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SupProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_customer', models.IntegerField(default=0)),
                ('name_product', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
