# Generated by Django 2.1.7 on 2019-04-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_sup_product_benefit_supbenefit_supproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sup_product_benefit',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SupBenefit'),
        ),
        migrations.AlterField(
            model_name='sup_product_benefit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SupProduct'),
        ),
    ]
