# Generated by Django 2.2.2 on 2020-03-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ngaysinh',
            field=models.DateField(auto_now=True, null=True, verbose_name='Ngày sinh'),
        ),
    ]
