# Generated by Django 2.2.2 on 2020-03-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ngaysinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hoten',
            field=models.CharField(max_length=30, null=True, verbose_name='Họ tên'),
        ),
    ]
