# Generated by Django 2.2.2 on 2020-03-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_updateuser'),
        ('users', '0002_user'),
    ]

    operations = [
    ]
