# Generated by Django 2.2.2 on 2020-03-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20200303_0454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateUser',
        ),
    ]
