# Generated by Django 2.2.2 on 2020-03-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_updateuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCTV',
        ),
    ]
