# Generated by Django 2.2.2 on 2020-03-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ben_mua_BH', models.CharField(max_length=200)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('ngay_dat_mua', models.DateTimeField(auto_now=True, null=True)),
                ('nguoi_GT', models.IntegerField(default=0)),
                ('ten_san_pham', models.CharField(max_length=155)),
                ('loai_san_pham', models.CharField(max_length=155)),
                ('congty', models.CharField(max_length=200)),
                ('phi_bao_hiem', models.IntegerField(default=0)),
                ('loai_hop_dong', models.IntegerField(default=0)),
            ],
        ),
    ]
