# Generated by Django 2.2.2 on 2020-03-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OderProductHomePortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sotienquybaohiem', models.CharField(max_length=200)),
                ('tylephi', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('sonamhopdong', models.IntegerField(default=0)),
                ('sonamdongphi', models.IntegerField(default=0)),
                ('home_age', models.IntegerField(max_length=200)),
                ('thanh_pho', models.CharField(max_length=200)),
                ('huyen', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('ma_hoa_don', models.CharField(max_length=200)),
                ('so_tien', models.IntegerField(default=0)),
                ('loai_san_pham', models.CharField(default='', max_length=200)),
                ('so_dien_thoai', models.CharField(max_length=200)),
                ('status1', models.IntegerField(default=0)),
                ('created_at', models.CharField(max_length=200)),
                ('vnp_TransactionNo', models.CharField(max_length=200)),
                ('product_id', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('secret', models.CharField(max_length=200)),
            ],
        ),
    ]
