# Generated by Django 2.2.2 on 2020-03-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_oderproducthomeportal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderproducthomeportal',
            name='home_age',
            field=models.IntegerField(default=0),
        ),
    ]
