# Generated by Django 2.2.2 on 2020-03-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contractinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinformation',
            name='product_frequency_phi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='product_insurance_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='product_phi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='supplementary_product_frequency_phi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='supplementary_product_insurance_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='supplementary_product_phi',
            field=models.IntegerField(default=0),
        ),
    ]
