# Generated by Django 2.2.2 on 2020-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20200302_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinformation',
            name='beneficiary_image',
            field=models.ImageField(null=True, upload_to='contract/'),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='buyer_image',
            field=models.ImageField(null=True, upload_to='contract/'),
        ),
        migrations.AlterField(
            model_name='contractinformation',
            name='receiver_image',
            field=models.ImageField(null=True, upload_to='contract/'),
        ),
    ]
