# Generated by Django 2.2.2 on 2020-03-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20200302_0441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderProductHomePortal',
            new_name='OderProductHomeModel',
        ),
    ]
