from django.urls import path
from . import views as dash_view
from . import  api as api_view
app_name = 'dashboard'

urlpatterns = [
    path('', dash_view.DashboardView.as_view(), name='dashboard'),
    path('life-contract/', dash_view.LifecontractView.as_view(), name='lifecontract'),
    path('non-life-contract/', dash_view.NonLifecontractView.as_view(), name='nonlifecontract'),
    path('add-life-contract/', dash_view.AddLifecontractView.as_view(), name='addlifecontract'),
    path('add-non-life-contract/', dash_view.AddLifenoncontractView.as_view(), name='addnonlifecontract'),
    path('customer/', dash_view.CustomerView.as_view(), name='customer'),
    path('personal-information/', dash_view.PersonalinformationView.as_view(), name='personalinformation'),
    path('changepassword/', dash_view.ChangepasswordView.as_view(), name='changepassword'),
    path('system-log/', dash_view.SystemlogView.as_view(), name='systemlog'),
    path('agent-total/', dash_view.AgenttotalView.as_view(), name='agenttotal'),
    path('new-agent/', dash_view.NewagentView.as_view(), name='newagent'),
    path('agent-channel/', dash_view.AgentchannelView.as_view(), name='agentchannel'),
    path('main-product/', dash_view.MainproductView.as_view(), name='mainproduct'),
    path('sup-product/', dash_view.SupproductView.as_view(), name='supproduct'),
    path('favorite-product/', dash_view.FavoriteproductView.as_view(), name='favoriteproduct'),
    path('calendar/', dash_view.CalendarView.as_view(), name='calendar'),
    path('inbox/', dash_view.InboxView.as_view(), name='inbox'),
    path('compose/', dash_view.ComposeView.as_view(), name='compose'),
    path('read/', dash_view.ReadView.as_view(), name='read'),
    path('user-agent/', dash_view.UseragentView.as_view(), name='useragent'),
    path('search-agent/', dash_view.SearchagentView.as_view(), name='searchagent'),
    path('nhan-tho/', dash_view.TrangThaiNhanTho.as_view(), name='nhantho'),
    path('phi-nhan-tho/', dash_view.TrangThaiPhiNhanTho.as_view(), name='phinhantho'),
    path('status-nhan-tho/', dash_view.StatusTrangThaiNhanTho.as_view(), name='statusnhantho'),
    path('status-phi-nhan-tho/', dash_view.StatusTrangThaiPhiNhanTho.as_view(), name='statusphinhantho'),
    path('add-nhan-tho/', dash_view.AddTrangThaiNhanTho.as_view(), name='addnhantho'),
    path('add-phi-nhan-tho/', dash_view.AddTrangThaiPhiNhanTho.as_view(), name='addphinhantho'),
    path('hd-moi/', dash_view.HdMoi.as_view(), name='hdmoi'),
    path('ls-hopdong/', dash_view.LichSuHopDong.as_view(), name='lshd'),
    path('duyet-kwc/', dash_view.DuyetCay.as_view(), name='duyetkwc'),
    path('status-duyet-kwc/', dash_view.StatusDuyetCay.as_view(), name='statusduyetkwc'),
    path('gan-nhom-kd/', dash_view.GanNhomKinhDoanh.as_view(), name='gannhomkd'),
    path('cay-gan-nhom-kinh-doanh/', dash_view.CayGanNhomKinhDoanh.as_view(), name='caygannhomkd'),
    path('tai-khoan/', dash_view.TaiKhoan.as_view(), name='taikhoan'),
    path('thongbao/', dash_view.thongbao.as_view(), name='thongbao'),
    path('tin-tuc/', dash_view.DaycontactView.as_view(), name='daycontact'),
    path('san-pham/', dash_view.ChannelcontactView.as_view(), name='channelcontact'),
    path('chinh-sach/', dash_view.ChinhSach.as_view(), name='chinh-sach'),
    path('tai-lieu/', dash_view.TaiLieu.as_view(), name='tai-lieu'),
    path('tong-quan-hd/', dash_view.TongQuanHopDong.as_view(), name='tongquanhd'),
    path('tong-quan-ctv/', dash_view.TongQuanCtv.as_view(), name='tongquanctv'),
    path('kpy', dash_view.KPY.as_view(), name='kpy'),
     path('status-tong-quan-hd/', dash_view.StatusTongQuanHopDong.as_view(), name='statustongquanhd'),
    path('status-tong-quan-ctv/', dash_view.StatusTongQuanCtv.as_view(), name='statustongquanctv'),
    path('status-kpy', dash_view.StatusKPY.as_view(), name='statuskpy'),
    #api url

    path('api/update-agency-total/', api_view.UpdateNumberAgencyTotal.as_view()),
    path('api/update-agency-new/', api_view.UpdateNumberNewAgency.as_view()),
    path('api/update-agency-channel/', api_view.UpdateNumberAgencyChannel.as_view()),
    path('api/update-number-customer-day/', api_view.UpdateNumberCustomerDay.as_view()),
    path('api/update-number-customer-month/', api_view.UpdateNumberCustomerMonth.as_view()),
    path('api/update-number-customer-location/', api_view.UpdateNumberCustomerLocation.as_view()),
    path('api/update-number-customer-channel/', api_view.UpdateNumberCustomerChannel.as_view()),
    path('api/update-day-success/', api_view.UpdateDaySuccess.as_view()),
    path('api/update-month-success/', api_view.UpdateMonthSuccess.as_view()),
    path('api/update-channel-success/', api_view.UpdateSuccessChannel.as_view()),
    path('api/update-main-product/', api_view.UpdateMainProductStatisticSuccess.as_view()),
    path('api/update-sup-product/', api_view.UpdateSupProductStatisticSuccess.as_view()),
    path('api/update-favorite-product/', api_view.UpdateFavoriteProductSuccess.as_view()),



]